runtime: nodejs22
env: standard
instance_class: F2

# Konfigurasi handler untuk melayani permintaan web
handlers:
- url: /
  script: auto

# Atur environment variables (opsional, tapi disarankan)
env_variables:
  NODE_ENV: 'production'
  PORT: '8080' # App Engine memerlukan port 8080
  # Tambahkan variabel lain yang diperlukan, contohnya untuk database
  # DB_HOST: '...'
  # DB_USER: '...'
  # DB_PASSWORD: '...'